accounts/urls.py
from django.urls import include, path, re_path
from accounts.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, LoginView, LogoutView, ProfileView, SignUpView, VisitorSignUpView #, CustomerSignUpView, SellerSignUpView, OwnerSignUpView, EditorSignUpView

from rest_framework_simplejwt import views as jwt_views
from accounts.api.views import UserList, UserDetail, RegisterUserView, UserLogoutView, UserProfileViewSet
from rest_framework.routers import DefaultRouter, SimpleRouter


router = SimpleRouter()
router.register(r'api/users/profiles', UserProfileViewSet)

app_name = 'accounts'
urlpatterns = router.urls + [
    #re_path(r'api/users/profiles', include('router.urls'), name='api_users_profiles'),
    path('api/login/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/login/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),    
    path('api/logout/', UserLogoutView.as_view(), name='api_users_logout'),
    path('api/users/', UserList.as_view(), name='api_users_list'),
    path('api/users/<int:pk>/', UserDetail.as_view(), name='api_users_detail'),
    path('api/register/', RegisterUserView.as_view(), name='api_signup'),
    
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/', PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetConfirmView.as_view(), name='password_reset_complete'),
    path('signin/', LoginView.as_view(), name='signin'),
    path('signout/', LogoutView.as_view(), name='signout'),
    path('profile/',ProfileView.as_view(), name='profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/visitor/', VisitorSignUpView.as_view(), name='visitor_signup'),
   # path('signup/customer/', CustomerSignUpView.as_view(), name='customer_signup'),
   # path('signup/seller/', SellerSignUpView.as_view(), name='seller_signup'),
   # path('signup/owner/', OwnerSignUpView.as_view(), name='owner_signup'),
   # path('signup/editor/', EditorSignUpView.as_view(), name='editor_signup'),
]

af/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.views.static import serve

from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from drf_openapi3.schemas.advanced import AdvancedSchemaGenerator
from rest_framework.schemas import get_schema_view
# from af.settings.production import MEDIA_ROOT, STATIC_ROOT



urlpatterns = [

    path('admin/', admin.site.urls),
    
    path('', include('fair.urls',  namespace='fair')),
    path('account/', include('drjr.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('products/', include('products.urls',  namespace='products')),
    path('fair_sites/', include('fair_sites.urls',  namespace='fair_sites')),
    path('businesses/', include('businesses.urls', namespace='businesses')),
    path('offers/', include('offers.urls',  namespace='offers'))
    #path('api-auth/', include('rest_framework.urls')),

    # Added Following Two Lines Of Code
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root': MEDIA_ROOT}), 
    # re_path(r'^static/(?P<path>.*)$', serve,{'document_root': STATIC_ROOT}), 
]

africafair/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.contrib.postgres.fields import CICharField, CIEmailField
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from af.core.models import TimestampModel
from accounts.managers import CustomUserManager
from af.settings.base import AUTH_USER_MODEL
from guardian.mixins import GuardianUserMixin

import uuid


def get_anonymous_user_instance(User):
    if User.objects.filter(email='anonymous@af.com').exists():
        return 1
    else:
        return User(first_name= 'John', last_name='Doe', email='anonymous@af.com', password='12345678')


class Role(models.Model):
  '''
  The Role entries are managed by the system,
  automatically created via a Django data migration.
  '''
  VISITOR = 1
  CUSTOMER = 2
  SELLER = 3
  OWNER = 4
  EDITOR = 5
  ROLE_CHOICES = (
      (VISITOR, 'visitor'),
      (CUSTOMER,'customer'),
      (SELLER, 'seller'),
      (OWNER, 'owner'),
      (EDITOR,'editor')
  )

  id = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, primary_key=True)

  def __str__(self):
      return self.get_id_display()


class CustomUser(AbstractBaseUser, PermissionsMixin, GuardianUserMixin):
    roles = models.ManyToManyField(Role)
    username_validator = ASCIIUsernameValidator()

    """username = CICharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_("Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )"""
    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    email = CIEmailField(
        _("email address"),
        unique=True,
        error_messages={
            "unique": _("A user with that email address already exists."),
        },
    )
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


class UserProfile(TimestampModel):
    """This model stores all information relative to a user which doesn't belong to
    authentication."""

    FRENCH = 'FR'
    ENGLISH = 'EN'
    LANGUAGE_CHOICE = [
        (FRENCH, 'français'),
        (ENGLISH, 'english'),
    ] 

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    user = models.OneToOneField(AUTH_USER_MODEL,
                                on_delete=models.CASCADE, 
                                related_name='profile')
    
    language_preference = models.CharField(max_length=2,
                                           choices=LANGUAGE_CHOICE,
                                           default=ENGLISH)
    def __str__(self):
        return self.user.email
    class Meta:
        permissions = (
            #('view_userprofile', 'View UserProfile'),
        )

accounts/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, UserChangeForm, AuthenticationForm
from django.db import transaction

from accounts.models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email' )


class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email' )


class CustomLoginForm(AuthenticationForm):

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['username'].widget.attrs.update(
      {'class': 'my-username-class'}
    )
    self.fields['password'].widget.attrs.update(
      {'class': 'my-password-class'}
    )


class CustomPasswordChangeForm(PasswordChangeForm):
    pass


class VisitorSignUpForm(CustomUserCreationForm):
    pass


"""
class VisitorSignUpForm(UserCreationForm):
    interests = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.interests.add(*self.cleaned_data.get('interests'))
        return user
"""

accounts/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import generics, mixins, status, viewsets
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework_guardian import filters
from rest_framework_simplejwt.tokens import RefreshToken 
from .serializers import CustomUserSerializer, UserProfileSerializer, RegisterSerializer, LogoutSerializer
from accounts.models import CustomUser, UserProfile


class UserList(generics.ListAPIView):
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['email', 'first_name', 'last_name']


class UserDetail(generics.RetrieveAPIView):
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer


class UserUpdate(generics.UpdateAPIView):
    queryset = CustomUser.objects.all()


class RegisterUserView(generics.CreateAPIView):
    queryset = CustomUser.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer


class UserLogoutView(APIView):
    serializer_class = LogoutSerializer
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response(status=status.HTTP_205_RESET_CONTENT)
        


""" class UserLogoutView(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        try:
            refresh_token = request.data["refresh_token"]
            token = RefreshToken(refresh_token)
            token.blacklist()

            return Response(status=status.HTTP_205_RESET_CONTENT)
        except Exception as e:
            return Response(status=status.HTTP_400_BAD_REQUEST) """


class UserProfileViewSet(viewsets.ModelViewSet):
    serializer_class = UserProfileSerializer
    queryset = UserProfile.objects.all()

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import redirect, resolve_url, reverse

from django.views.generic import CreateView
from django.views.generic.base import TemplateView, RedirectView

from accounts.models import CustomUser
from accounts.forms import CustomLoginForm, CustomPasswordChangeForm, VisitorSignUpForm



class LoginView(auth_views.LoginView):
    template_name = 'registration/login.html'
    authentication_form = CustomLoginForm

    def get_success_url(self):
        return resolve_url('accounts:login')
    
    def get_success_url_allowed_hosts(self):
        return super().get_success_url_allowed_hosts()


class LogoutView(auth_views.LogoutView):
    """
    A view that logout user and redirect to homepage.
    """
    template_name = 'registration/logout.html'
    permanent = False
    query_string = True
    pattern_name = 'fair:index'

    def get_redirect_url(self, *args, **kwargs):
        """
        Logout user and redirect to target url.
        """
        if self.request.user.is_authenticated():
            logout(self.request)
        return super(LogoutView, self).get_redirect_url(*args, **kwargs)


class PasswordChangeView(auth_views.PasswordChangeView):
    template_name = 'registration/password_change.html'
    form_class = CustomPasswordChangeForm
    success_url = 'accounts:password_change_done'


class PasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    template_name = 'registration/password_change_done.html'


class PasswordResetView(auth_views.PasswordResetView):
    template_name = 'registration/password_change.html'
    success_url = 'accounts:password_reset_done'


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'registration/password_reset_done.html'
    success_url = 'accounts:password_reset_confirm'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    success_url = 'accounts:password_reset_complete'

class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'registration/password_reset_complete.html'  


class SignUpView(TemplateView):
    template_name = 'accounts/signup.html'


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'


class VisitorSignUpView(CreateView):
    model = CustomUser
    form_class = VisitorSignUpForm
    template_name = 'accounts/visitor_signup_form.html'

    def get_context_data(self, **kwargs):  
        kwargs['user_type'] = 'visitor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('fair:home')

templates/accounts/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <!-- Media object -->
                    <div class="d-flex">
                        <!-- Image -->
                        <img
                                src="{{ user.profile.image.url }}"
                                alt="{{ user.username }}"
                                class="me-3 rounded-circle"
                                style="width: 70px; height: 70px;"
                        />
                        <!-- Body -->
                        <div>
                            <h3 class="fw-bold">
                                {{ user.username }} -
                                <small class="text-muted">
                                    Updated on {{ user.profile.updated_at|date:"SHORT_DATE_FORMAT" }}
                                </small>
                            </h3>
                            <p class="text-secondary">{{ user.profile.role_play.name }}, {{ user.email }}</p>

                        </div>
                    </div>
                    <!-- Media object -->

                    <form class="form-control form-control-lg" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="form-group ">
                            <legend class="border-bottom mb-4">Profile Info</legend>
                            {{ u_form|crispy }}
                            {{ p_form|crispy }}
                        </fieldset>
                        <div class="row justify-content-center">
                            <button class="btn btn-outline-info" type="submit">
                                Update
                            </button>
                        </div>
                    </form>

                </div>
                <div class="col-xl-6">
                    <div class="bg-primary w-auto m-auto rounded-lg p-8 my-8 text-primary">
                        <h2 class="border-bottom border-light ">Refer a friend and win bonuses</h2>
                        <p class="border-bottom border-light ">
                            To take the full benefit from africa fair,
                            refer a friend and win bonuses based on his purchased
                        </p>
                        {# include "forms.field" #}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/signin.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block content %}

        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Sign up ! </h1>
                            <h2 class="mb-5">for a free account</h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Icons Grid-->
        <section class="features-icons bg-light">
            <div class="container">
                <div class="row">
                  <div class="col-md-8 col-sm-10 col-12">
                    <h2>Sign up as a {{ user_type }}</h2>
                    <form method="post" novalidate>
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ next }}">
                      {{ form|crispy }}
                      <button type="submit" class="btn btn-success">Sign up</button>
                    </form>
                  </div>
                </div>
            </div>
        </section>
       

{% endblock content %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Sign up ! </h1>
                            <h2 class="mb-5">for a free account</h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Icons Grid-->
        <section class="features-icons bg-light text-center">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                            <div class="features-icons-icon d-flex"><i class="bi-window m-auto text-primary"></i></div>
                            
                            <p class="lead mb-0">Select below the type of account you want to create</p>
                            <a href="{% url 'accounts:visitor_signup' %}" class="btn btn-student btn-lg" role="button">I'm a visitor</a>
                            <a href="{# url 'accounts:owner_signup' #}" class="btn btn-teacher btn-lg" role="button">I'm a shop owner</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
       

{% endblock content %}

templates/accounts/visitor_signup_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block content %}

        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Sign up ! </h1>
                            <h2 class="mb-5">for a free account</h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Icons Grid-->
        <section class="features-icons bg-light">
            <div class="container">
                <div class="row">
                  <div class="col-md-8 col-sm-10 col-12">
                    <h2>Sign up as a {{ user_type }}</h2>
                    <form method="post" novalidate>
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ next }}">
                      {{ form|crispy }}
                      <button type="submit" class="btn btn-success">Sign up</button>
                    </form>
                  </div>
                </div>
            </div>
        </section>
       

{% endblock content %}