accounts/urls.py
from django.urls import include, path, re_path
from accounts.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, LoginView, LogoutView, ProfileView, SignUpView, VisitorSignUpView #, CustomerSignUpView, SellerSignUpView, OwnerSignUpView, EditorSignUpView

from rest_framework_simplejwt import views as jwt_views
from accounts.api.views import UserList, UserDetail, RegisterUserView, UserLogoutView, UserProfileViewSet
from rest_framework.routers import DefaultRouter, SimpleRouter


router = SimpleRouter()
router.register(r'api/users/profiles', UserProfileViewSet)

app_name = 'accounts'
urlpatterns = router.urls + [
    #re_path(r'api/users/profiles', include('router.urls'), name='api_users_profiles'),
    path('api/login/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/login/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),    
    path('api/logout/', UserLogoutView.as_view(), name='api_users_logout'),
    path('api/users/', UserList.as_view(), name='api_users_list'),
    path('api/users/<int:pk>/', UserDetail.as_view(), name='api_users_detail'),
    path('api/register/', RegisterUserView.as_view(), name='api_signup'),
    
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/', PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetConfirmView.as_view(), name='password_reset_complete'),
    path('signin/', LoginView.as_view(), name='signin'),
    path('signout/', LogoutView.as_view(), name='signout'),
    path('profile/',ProfileView.as_view(), name='profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/visitor/', VisitorSignUpView.as_view(), name='visitor_signup'),
   # path('signup/customer/', CustomerSignUpView.as_view(), name='customer_signup'),
   # path('signup/seller/', SellerSignUpView.as_view(), name='seller_signup'),
   # path('signup/owner/', OwnerSignUpView.as_view(), name='owner_signup'),
   # path('signup/editor/', EditorSignUpView.as_view(), name='editor_signup'),
]

af/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.views.static import serve

from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from drf_openapi3.schemas.advanced import AdvancedSchemaGenerator
from rest_framework.schemas import get_schema_view
# from af.settings.production import MEDIA_ROOT, STATIC_ROOT



urlpatterns = [

    path('admin/', admin.site.urls),
    
    path('', include('fair.urls',  namespace='fair')),
    path('account/', include('drjr.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('products/', include('products.urls',  namespace='products')),
    path('fair_sites/', include('fair_sites.urls',  namespace='fair_sites')),
    path('businesses/', include('businesses.urls', namespace='businesses')),
    path('offers/', include('offers.urls',  namespace='offers'))
    #path('api-auth/', include('rest_framework.urls')),

    # Added Following Two Lines Of Code
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root': MEDIA_ROOT}), 
    # re_path(r'^static/(?P<path>.*)$', serve,{'document_root': STATIC_ROOT}), 
]

africafair/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

fair/urls.py
from django.urls import include, path
from fair.views import IndexView, HomeView, AboutView

"""
handler404 = 'fair.views.error_404'
handler500 = 'fair.views.error_500'
handler403 = 'fair.views.error_403'
handler400 = 'fair.views.error_400'
"""

app_name = 'fair'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('home/', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    
]

templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Africa Fair - Portal</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{%  static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-md navbar-light bg-light static-top">
    <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'fair:index' %}">Afric@FAIR</a>
        <div class="navbar-nav mr-auto">
            <a class="nav-link" href="{% url 'fair:index' %}">Welcome</a>
            <a class="nav-link" href="{% url 'fair:about' %}">About</a>
        </div>
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="btn btn-link" href="{% url 'fair:home' %}">My Fair</a>
                <a class="btn btn-link" href="{% url 'accounts:profile' %}">Profile</a>
                <a class="btn btn-outline-secondary" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-link" href="{% url 'accounts:login' %}">Login</a>
                <a class="btn btn-primary" href="{% url 'accounts:signup' %}">Signup</a>
            {% endif %}

        </div>
    </div>
</nav>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% block content %}{% endblock content %}
<!-- Footer-->
<footer class="footer bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                <ul class="list-inline mb-2">
                    <li class="list-inline-item"><a href="#!">About</a></li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item"><a href="#!">Contact</a></li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2021. All Rights Reserved.</p>
            </div>
            <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item me-4">
                        <a href="#!"><i class="bi-facebook fs-3"></i></a>
                    </li>
                    <li class="list-inline-item me-4">
                        <a href="#!"><i class="bi-twitter fs-3"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!"><i class="bi-instagram fs-3"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>

</body>
</html>

templates/base_bkp.html
{% load static %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Django School{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontello-2f186091/css/fontello.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    {% if user.is_authenticated and user.is_teacher %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/teachers.css' %}">
    {% else %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/students.css' %}">
    {% endif %}
  </head>
  <body>
    <a href="https://github.com/sibtc/django-multiple-user-types-example"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"></a>
    <div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="row">
            <div class="col-6">
              <h1 class="logo">
                <a href="{# url 'home' #}">
                  Django School
                  {% if user.is_authenticated %}
                    {% if user.is_teacher %}
                      <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Teacher profile"></span>
                    {% else %}
                      <span class="icon-graduation-cap" data-toggle="tooltip" data-placement="right" title="Student profile"></span>
                    {% endif %}
                  {% endif %}
                </a>
              </h1>
            </div>
            <div class="col-6 text-right">
              {% if user.is_authenticated %}
                <p class="pt-3">Logged in as <strong>{{ user.username }}</strong>. <a href="{% url 'accounts:logout' %}">Log out</a>.</p>
              {% else %}
                <a href="{%url 'accounts:login' %}" class="btn btn-light" role="button">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary" role="button">Sign up</a>
              {% endif %}
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% block content %}
              {% endblock %}
            </div>
          </div>
          <footer>
            <a href="https://simpleisbetterthancomplex.com">© SimpleIsBetterThanComplex.com</a>
            /
            <a href="https://simpleisbetterthancomplex.com/tutorial/2018/01/18/how-to-implement-multiple-user-types-with-django.html">Read more about this example</a>
            /
            <a href="https://github.com/sibtc/django-multiple-user-types-example">GitHub repository</a>
          </footer>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
    </script>
  </body>
</html>